import "./globals.css";
import type { Metadata } from "next";
import { Inter, Mansalva } from "next/font/google";
import Navbar from "./components/Navbar";
import { Provider } from "./components/Provider";
import Contact from "./Contact/page";
import Projects from "./Projects/page";
import Mantra from "./Mantra/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-white text-black dark:bg-[#090908] dark:text-white h-full selection:bg-gray-50 dark:selection:bg-gray-800`}
      >
        <Provider>
          <Navbar />
          <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 space-y-40">
            {children}
            <Projects/>
          <Mantra/>
          <Contact/>
          </main>
         
        </Provider>
      </body>
    </html>
  );
}
